# handlers file for keepalived
---
- name: restart keepalived
  service:
    name: keepalived
    state: restarted

- name: restart conntrackd
  service:
    name: conntrackd
    state: restarted

- name: reload keepalived
  service:
    name: keepalived
    state: reloaded


#- name: reload keepalived
#  command: service keepalived reload
