# handlers file for keepalived
---
- name: restart keepalived
  service:
    name: keepalived
    state: restarted

- name: reload keepalived
  sudo: yes
  command: service keepalived reload

# by some reason it doesn't work
#- name: reload keepalived
#  service:
#    name: keepalived
#    state: reloaded
